### ISSUE TITLE
Problems launching Emacs after building .deb package

### ISSUE THREAD

**Issue by peterwvj** [konstare/emacs-gcc-pgtk#2]
I build the .deb package according to the instructions in the README and installed the .deb package. Now when I run, Emacs I get the following errors:

```
emacs: /lib/x86_64-linux-gnu/libselinux.so.1: no version information available (required by emacs)
emacs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by emacs)
```

System specs:

```
λ uname -a
Linux laptop 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by konstare** [comment]
>62~20.04.1-Ubuntu

Sorry the deb package is built for Ubuntu 20.10 not 20.04. You can try to change the first line of the Docker file from "FROM ubuntu:20.10" to "FROM ubuntu:20.04". But I doubt it will work either due to some problems with libgccjit. Maybe the libgccjit problems for 20.04 were fixed maybe not. I do not know.

If you are interested, you can try to revive this version of the Dockerfile, which deals with the libgccjit mess: https://github.com/hackenbergstefan/emacs-jit-build

**Comment by peterwvj** [comment]
Yes, you are very right, thanks :) I'll try to build with 20.04 and see where that takes me.

**Comment by peterwvj** [comment]
I came across [this blog](http://www.cesarolea.com/posts/emacs-native-compile/) which provides instructions for how to get this to work on 20.04. Hope someone else might find this helpful.
